---

- name: Install required dependencies
  dnf:
    name: ['openjdk-latest-jdk', 'byobu']
    state: present
  when: ansible_os_family == "Redhat"
  tags: [development]

- name: Install required dependencies
  apt:
    name: ['openjdk-13-jdk', 'byobu']
    state: present
  when: ansible_os_family == "Debian"
  tags: [development]

- name: Upgrade all installed Packages
  apt:
    update_cache: yes
    upgrade: yes
  when: ansible_os_family == "Debian"
  tags: [development]

- name: Upgrade all installed Packages
  dnf:
    update_cache: yes
    upgrade: yes
  when: ansible_os_family == "Redhat"
  tags: [development]
