---

- name: Install required dependencies
  package:
    name: "{{item}}"
    state: present
  with_items:
    - openjdk-9-jre
    - git
    - byobu
  tags: [development]

- name: Install OpenJDK 9
  apt:
    name: "openjdk-9-jdk"
    state: present
    dpkg_options: "force-overwrite"
  when: ansible_os_family == "Debian"
  tags: [development]

- name: Allow Byobu to start by default
  shell: byobu-enable
  become_user: vagrant
  tags: [development]

- name: Upgrade all installed Packages
  apt:
    update_cache: yes
    upgrade: yes
  tags: [development]
