---

- name: Install required dependencies
  yum:
    name: ['java-latest-openjdk-devel', 'byobu']
    state: present
  tags: [development]

- name: Upgrade all installed Packages
  apt:
    update_cache: yes
    upgrade: yes
  tags: [development]
