---

- name: Install required dependencies
  yum:
    name: "{{item}}"
    state: present
  with_items:
    - java-1.8.0-openjdk-devel
    - git2u
    - byobu
  tags: [development]

# - name: Allow Byobu to start by default
#   shell: byobu-enable
#   become_user: vagrant
#   tags: [development]

- name: Upgrade all installed Packages
  yum:
    name: '*'
    state: latest
  tags: [development]
