---

- name: Include required variables
  include_vars: "../vars/default.yml"
  tags: [emacs]

# - name: Install supporting packages to compile Emacs
#   yum:
#     name: ['gcc', 'make', 'gnutls-devel', 'ncurses-devel', 'giflib-devel', 'libjpeg-devel', 'libtiff-devel']
#     state: present
#   tags: [emacs]
#
# - name: Download latest Emacs package
#   get_url:
#     url: http://ftp.gnu.org/gnu/emacs/{{ emacs_version }}.tar.gz
#     dest: /home/vagrant/{{ emacs_version }}.tar.gz
#     owner: vagrant
#     group: vagrant
#   when: emacs_present.stat.exists == False
#   tags: [emacs]
#
# - name: Extract the package
#   unarchive:
#     src: /home/vagrant/{{ emacs_version }}.tar.gz
#     dest: /home/vagrant/
#     remote_src: yes
#     group: vagrant
#     owner: vagrant
#   become_user: vagrant
#   when: emacs_present.stat.exists == False
#   tags: [emacs]
#
# - name: Configure and make the package
#   shell: |
#     ./configure --with-mailutils --without-x --without-selinux
#
#     make
#
#     sudo make install
#   args:
#     chdir: ~/{{ emacs_version }}
#   become_user: vagrant
#   when: emacs_present.stat.exists == False
#   tags: [emacs]

- name: Install emacs
  dnf:
    name: emacs-nox
    state: latest
  when: ansible_os_family == "Redhat"
  tags: [emacs]

- name: Install emacs
  apt:
    name: emacs26-nox
    state: latest
  when: ansible_os_family == "Debian"
  tags: [emacs]

- name: Create .emacs.d folder if not present
  file:
    path: /home/vagrant/.emacs.d
    state: directory
    owner: vagrant
    group: vagrant
    mode: "u=rwx,o=r,g=r"
  tags: [emacs]

- name: Downloading Emacs Prelude
  get_url:
    url: https://raw.githubusercontent.com/bbatsov/prelude/master/utils/installer.sh
    dest: /tmp/
    mode: 0755
  become: yes
  tags: [emacs]

- name: Install Prelude
  shell: /tmp/installer.sh
  args:
    chdir: /tmp/
    executable: /bin/sh
  become: vagrant
  tags: [emacs]

- name: Configure prelude modules to be loaded by default
  copy:
    src: prelude-modules.el
    dest: /home/vagrant/.emacs.d/personal/prelude-modules.el
    owner: vagrant
    group: vagrant
  tags: [emacs]

- name: Require custom packages
  copy:
    src: require-packages.el
    dest: /home/vagrant/.emacs.d/personal/require-packages.el
    owner: vagrant
    group: vagrant
  tags: [emacs]

- name: Set default theme
  copy:
    src: set-theme.el
    dest: /home/vagrant/.emacs.d/personal/preload/set-theme.el
    owner: vagrant
    group: vagrant
  tags: [emacs]

- name: Create site-lisp folder if it doesn't exist
  file:
    path: /home/vagrant/.emacs.d/site-lisp
    state: directory
    mode: "u=rwx,o=r,g=r"
    owner: vagrant
    group: vagrant
  tags: [emacs]

- name: Copy duplicate line macro
  copy:
    src: duplicate-line.el
    dest: /home/vagrant/.emacs.d/site-lisp/duplicate-line.el
    owner: vagrant
    group: vagrant
  tags: [emacs]
