- name: Install useful command line tools
  package:
    name: ['git', 'wget', 'telnet', 'htop', 'unzip', 'ngrep', 'tig', 'bat']
    state: present
  tags: [setup]

- name: Setup timezone to be local
  become: yes
  command: timedatectl set-timezone Asia/Kolkata
  when: ansible_os_family == "Debian"
  tags: [setup]

- include_tasks: repo.yml
- include_tasks: zsh.yml
