- include_tasks: repo.yml
- include_tasks: zsh.yml

- name: Install useful command line tools
  package:
    name: "{{item}}"
    state: present
  with_items:
    - wget
    - telnet
    - ntp
    - htop
    - unzip
    - tig
  tags: [setup]

- name: Setup timezone to be local
  become: yes
  command: timedatectl set-timezone Asia/Kolkata
  when: ansible_os_family == "Debian"
  tags: [setup]
