- name: Add Extended Packages for Enterprise Linux repository
  yum:
    name: epel-release
    state: present
  tags: [setup]

- name: Add IUS repository
  yum:
    name: https://centos7.iuscommunity.org/ius-release.rpm
    state: present
  tags: [setup]

- name: Add REMI repository
  yum:
    name: http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
    state: present
  tags: [setup]

- name: Install useful command line tools
  yum:
    name: "{{item}}"
    state: present
  with_items:
    - wget
    - telnet
    - ntp
    - htop
    - tig
  tags: [setup]
