- name: Add required PPA
  apt_repository:
    repo: "{{ item }}"
  with_items:
    - ppa:git-core/ppa
    - ppa:openjdk-r/ppa
    - ppa:kelleyk/emacs
  when: ansible_os_family == "Debian"
  tags: [setup]

- name: Install Aptitude
  apt:
    pkg: "aptitude"
    state: latest
    update_cache: yes
  when: ansible_os_family == "Debian"
  tags: [setup]

- name: Install useful command line tools
  package:
    name: "{{item}}"
    state: present
  with_items:
    - wget
    - telnet
    - ntp
    - htop
    - unzip
    - tig
  tags: [setup]

- name: Setup timezone to be local
  become: yes
  command: timedatectl set-timezone Asia/Kolkata
  when: ansible_os_family == "Debian"
  tags: [setup]
